use_frameworks!

target 'RippleKit_Example' do
  pod 'RippleKit', :path => '../'

  target 'RippleKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
